# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
name: jasonhodges.me
description: Jason Hodges is a Software Engineer located in Denver Colorado specializing in Angular, TDD, Redux, & D3.
url: jasonhodges.me

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: dist
exclude: ['assets']

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
# NOTE: Don't use @ in front of your Twitter username
author:
  name: Jason Hodges
  email: jason@jasonhodges.me
  uri: jasonhodges.me
  bio:
  twitter: _jasonhodges
  github: jasonhodges
  linkedin: jasonhodges09

# Resume settings
resume_avatar:          true
resume_name:            Jason Hodges
resume_title:           Software Engineer
resume_contact_email:   jason@jasonhodges.me

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: false
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
permalink: none
paginate: 10
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

# Markdown library and options
#highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']

#pygments: true
# Extending Jekyll
gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

# Settings for archives
jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layouts:
    year: 'year-archive'
    month: 'month-archive'
    category: 'category-archive'
    tag: 'tag-archive'
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/:month/'
    category: '/category/:name/'
    tags: '/tag/:name/'


# Resume Settings
resume_avatar:    'true'
resume_name:      'Jason Hodges'
resume_title:     'Software Engineer'
resume_email:     'jason@jasonhodges.me'

resume_available: 'yes'
