name: 'JasonHodges.me'
url: 'http://jasonhodges.me'
author: 'Jason Hodges'
# paginate: 5
# paginate_path: "/blog/page:num/"
# permalink : /blog/:categories/:title
timezone: 'America/Indiana'
pygments: true
markdown: rdiscount
exclude : ["*.orig", "readme.md", "*.todo", "*.scss", "Guardfile", "*.sublime-*", "config.rb", "Rakefile"]
