name: 'JasonHodges.me'
url: 'http://jasonhodges.me'
author: 'Jason Hodges'

include: ['_pages']

paginate: 10
paginate_path: '/blog/page:num/'
permalink: '/blog/:year/:title/'
relative_permalinks: false

excerpt_seperator: "{{more}}"

timezone: 'America/Indiana'

safe: true
markdown: maruku
pygments: false
